<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="wetechnolabs13" failures="1" tests="4" name="TestPackage.TestCase_Bucket_lead_distribution" time="56.393" errors="0" timestamp="2024-09-26T03:49:28 GMT-04:00" skipped="3">
  <testcase classname="TestPackage.TestCase_Bucket_lead_distribution" name="Verify_the_Leads_distribution_From_bucket" time="12.784">
    <skipped/>
  </testcase> <!-- Verify_the_Leads_distribution_From_bucket -->
  <system-out/>
  <testcase classname="TestPackage.TestCase_Bucket_lead_distribution" name="Verify_the_Leads_distribution_From_bucket" time="18.291">
    <skipped/>
  </testcase> <!-- Verify_the_Leads_distribution_From_bucket -->
  <system-out/>
  <testcase classname="TestPackage.TestCase_Bucket_lead_distribution" name="Verify_the_Leads_distribution_From_bucket" time="13.605">
    <skipped/>
  </testcase> <!-- Verify_the_Leads_distribution_From_bucket -->
  <system-out/>
  <testcase classname="TestPackage.TestCase_Bucket_lead_distribution" name="Verify_the_Leads_distribution_From_bucket" time="11.713">
    <failure message="The following asserts failed:
	The Leads Distribution from bucket is not Working perfect" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
The Leads Distribution from bucket is not Working perfect
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at PomPackage.Pom_Bucket_leads_distribution_check.Action_on_Bucket_leads_statistics(Pom_Bucket_leads_distribution_check.java:102)
at TestPackage.TestCase_Bucket_lead_distribution.Verify_the_Leads_distribution_From_bucket(TestCase_Bucket_lead_distribution.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Verify_the_Leads_distribution_From_bucket -->
  <system-out/>
</testsuite> <!-- TestPackage.TestCase_Bucket_lead_distribution -->
